### ISSUE TITLE
[3338-v12] Drills that have gone offscreen make no sound.

### ISSUE THREAD

**Issue by Hobey** [AsuMagic/kag-staging#99] opened 2020-09-04 21:28 UTC
How to reproduce:

Go into sandbox
Put a tunnel on the left of the map, suicide until you are on the right side, put tunnel on the right side
Make a drill and notice that it does make sound
Drop the drill on the ground and go through tunnel and come back
Notice that the drill makes no sound when you use it

**Comment by AsuMagic** [comment] 2020-11-01 10:07
Sounds like this is caused by inaudible sounds getting killed when inaudible. Emit sounds are only paused when they quit playing, not destroyed then replayed. The fix isn't quite obvious because the "must tick" behavior of soloud is glitchy and inappropriate anyway.

**Comment by AsuMagic** [comment] 2020-11-01 10:39
Actually for emit sounds it's fairly easy to work around, so that will be fixed in `3484-render2d-v4`

**Comment by AsuMagic** [comment] 2021-09-29 22:33
Should be fixed in 3570-render2d-v3 when it's out

**Closed by AsuMagic** 2021-09-29 22:33 UTC
Labels: bug, audio, done
